core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memory.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memory/urls.py
from django.urls import path, include
from .views import DeleteMemory, UpdateMemory
from . import views
from django.urls import path, re_path, include


app_name = "memory"

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('django.contrib.auth.urls')),
    path('registration/', views.registration, name="registration"),
    path('gallery/', views.gallery, name='gallery'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('remembering/<str:pk>/', views.viewRemembering, name='remembering'),
    path('remembering/<str:pk>/update', UpdateMemory.as_view(), name='update'),
    path('remembering/<str:pk>/delete', DeleteMemory.as_view(), name="delete"),
    path('add/', views.addMemory, name='add'),
]

memory/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Memory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=50, default=None)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(null=False, upload_to="images/", blank=False)
    description = models.TextField()
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Ваш код для автоматического заполнения полей latitude и longitude на основе address
        if not self.latitude or not self.longitude:
            geolocator = Nominatim(user_agent="memory")
            location = None
            try:
                location = geolocator.geocode(self.address)
            except GeocoderTimedOut as e:
                # Обработка ошибок геокодера
                print(f"Geocoding error: {e}")
            
            if location:
                self.latitude = location.latitude
                self.longitude = location.longitude

        super().save(*args, **kwargs)
    
    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)
    
    def __str__(self):
        return self.description

memory/forms.py
from django import forms
from .models import Memory, Category
from django.forms import ModelForm, TextInput, Textarea, FileInput

class MemoryForm(ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False, label='Выбрать категорию')
    new_category_name = forms.CharField(max_length=100, required=False, label='Или создать новую категорию')
    
    class Meta:
        model = Memory
        fields = [ 'title', 'description', 'image', 'category', 'new_category_name', 'latitude', 'longitude', 'address']

        labels = {
            'title': "",
            'description': "",
            'image': "Выберете изображение",
        }

        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название Воспоминания'
                
            }),
            "description": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Полное Впечетление',
            }),
            'address': forms.HiddenInput(),
            'latitude': forms.HiddenInput(),
            'longitude': forms.HiddenInput(),
        }
        def __init__(self, *args, **kwargs):
            user = kwargs.pop('user', None)
            super(MemoryForm, self).__init__(*args, **kwargs)
            if user:
                self.fields['category'].queryset = Category.objects.filter(user=user)

        def clean(self):
            cleaned_data = super().clean()
            category = cleaned_data.get('category')
            new_category_name = cleaned_data.get('new_category_name')

            if not category and not new_category_name:
                raise forms.ValidationError("Выберите существующую категорию или укажите новую")

            return cleaned_data
        
        

memory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Category, Memory
from .forms import MemoryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

def index(request):
    return render(request, 'registration/index.html')

def registration(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('memory:login')
    context = {"form": form}
    return render(request, 'registration/registration.html', context=context)

@login_required
def gallery(request):
    user_memories = Memory.objects.filter(user=request.user)
    user_categories = Category.objects.filter(user=request.user)
    category = request.GET.get('category')
    if category == None:
        memories = user_memories.all()
    else:
        memories = user_memories.filter(category__name=category)

    categories = user_categories
    context = {'categories': categories, 'memories': memories}
    return render(request, 'memory/gallery.html', context)

@login_required
def viewRemembering(request, pk):
    memory = Memory.objects.get(id=pk)
    return render(request, 'memory/remembering.html', {'memory': memory})

@login_required
def addMemory(request):
    categories = Category.objects.filter(user=request.user)

    if request.method == "POST":
        form = MemoryForm(request.POST, request.FILES)
        if form.is_valid():
            memory = form.save(commit=False)
            memory.user = request.user

            category = form.cleaned_data['category']
            new_category_name = form.cleaned_data['new_category_name']

            if category:
                memory.category = category
            elif new_category_name:
                new_category = Category.objects.create(name=new_category_name, user=request.user)
                memory.category = new_category
            memory.save()
            return redirect('memory:gallery')
    else:
        form = MemoryForm()
        form.user = request.user
        form.fields['category'].queryset = categories

    context = {'categories': categories, 'form': form}
    return render(request, 'memory/add.html', context)

@login_required
def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)

    if category.memory_set.count() == 0:
        category.delete()
        return redirect('memory:gallery')
    else:
        return redirect('memory:gallery')

class DeleteMemory(DeleteView):
    model = Memory
    template_name = "memory/delete_remember.html"
    context_object_name = "post"
    success_url = reverse_lazy("memory:gallery")

class UpdateMemory(UpdateView):
    model = Memory  # Используйте модель Memory, а не форму MemoryForm
    form_class = MemoryForm  # Укажите класс вашей формы
    template_name = "memory/add.html"
    success_url = reverse_lazy("memory:gallery")

    def form_valid(self, form):
        memory = form.save(commit=False)
        memory.user = self.request.user

        category = form.cleaned_data['category']
        new_category_name = form.cleaned_data['new_category_name']

        if category:
            memory.category = category
        elif new_category_name:
            new_category = Category.objects.create(name=new_category_name, user=self.request.user)
            memory.category = new_category

        memory.save()
        return super().form_valid(form)

memory/templates/memory/add.html
{% extends "memory/base.html" %}

{% block title %}Добавить Воспоминание{% endblock title%}

{% block content %}
<div class="">
  <div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <a href="{% url 'memory:gallery' %}" 
            class="btn btn-dark my-3">Вернутся в галлерею</a>
            <div class="card">
                <form method="POST" action="" enctype="multipart/form-data" style="color: white;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p>Добавте местоположение:</p>
                    <div id="map" style="width: 100%; height: 400px;"></div>

                    <button type="submit" class="btn btn-primary m-4" id="saveButton" disabled>Сохранить новое воспоминание</button>

                </form>
            </div>
        </div>
    </div>
  </div>
  <script src="https://api-maps.yandex.ru/2.1/?apikey=6f23e260-3f4c-4ffb-9804-554d9b4dcbf9&lang=ru_RU" type="text/javascript">
  </script>
  <script>
  ymaps.ready(init);

  function init() {
    var map = new ymaps.Map('map', {
      center: [0, 0],
      zoom: 2
    });

    var placemark = new ymaps.Placemark([0, 0], {
      hintContent: 'Перетащите метку для выбора местоположения'
    }, {
      draggable: true
    });

    map.geoObjects.add(placemark);

    placemark.events.add('dragend', function (e) {
      var coords = placemark.geometry.getCoordinates();
      document.getElementById('id_latitude').value = coords[0];
      document.getElementById('id_longitude').value = coords[1];
      checkFormValidity();
    
      ymaps.geocode(coords).then(function (res) {
        var firstGeoObject = res.geoObjects.get(0);

        // Используйте getCountry() и getAdministrativeAreas() для получения адреса
        var country = firstGeoObject.getCountry();
        var adminAreas = firstGeoObject.getAdministrativeAreas();

        // Соберем адрес из полученных частей
        var address = [country, adminAreas.join(', ')].filter(Boolean).join(', ');

        // Выведем адрес в консоль для отладки
        console.log('Адрес:', address);

        // Установим адрес в поле формы
        document.getElementById('id_address').value = address;
      }).catch(function (error) {
        console.error('Ошибка геокодирования:', error);
      });
    });
    
  }
  function checkFormValidity() {
      var saveButton = document.getElementById('saveButton');
      var latitudeInput = document.getElementById('id_latitude');
      var longitudeInput = document.getElementById('id_longitude');
      var latitude = parseFloat(latitudeInput.value);
      var longitude = parseFloat(longitudeInput.value);

      if (!isNaN(latitude) && !isNaN(longitude)) {
        saveButton.disabled = false;
      } else {
        saveButton.disabled = true;
      }
    }
    document.addEventListener("DOMContentLoaded", function() {
            var yourElement = document.querySelector(".hak");
            var scrollThreshold = 1; // Установите порог прокрутки, после которого position будет отменен

            window.addEventListener("scroll", function() {
                if (window.scrollY > scrollThreshold) {
                    yourElement.classList.add("non_position");
                } else {
                    yourElement.classList.remove("non_position");
                }
            });
        });
  </script>
</div>
{% endblock content%}

memory/templates/memory/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'memory/css/memory.css' %}">
    <style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }
        .hak {
            animation: animate 18s ease-in-out infinite;
            min-width: 240px;
        }
        @keyframes animate{
            0%,100%{
                background-image: url("{% static 'memory/images/forest.jpg'%}");
            }
            30%{
                background-image: url("{% static 'memory/images/forest1.jpg'%}");
            }
            50%{
                background-image: url("{% static 'memory/images/forest2.jpg'%}");
            }
            75%{
                background-image: url("{% static 'memory/images/forest3.jpg'%}");
            }
            
        }
        header {
            background-image: url("{% static 'memory/images/romb.jpg'%}");
            background-size: cover;
        }
        .card {
            background-image: url("{% static 'memory/images/romb_list.jpg'%}");
            background-size: cover;
        }
        
    </style>
</head>
<body>
    <div class="hak">
        <header>
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#"><p>Places Remember</p></a>
                    <div class="nav justify-content-end" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            {% if user.is_authenticated %}
                                {% if user.first_name %}
                                    <a href="{% url 'memory:logout' %}?next={% url 'memory:index' %}" style="text-decoration: none;"
                                    class="btn btn-primary">Выйти</a>
                                {% else %}
                                    <a href="{% url 'memory:logout' %}?next={% url 'memory:index' %}" style="text-decoration: none;"
                                    class="btn btn-primary">Выйти</a>
                                {% endif %}
                            {% else %}
                                
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        {% block content %}
        {% endblock content%}
    </div>
</body>
</html>

memory/templates/memory/gallery.html
{% extends "memory/base.html" %}

{% block title %}Галлерея{% endblock title%}
{% block content %}
<style>
.col-md-3 {
    min-width: 240px;
}

</style>
<div class="m-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <div class="card">
                    <div class="card-header" style="color: white;">
                    Категории
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'memory:gallery' %}" style="text-decoration: none;">Все Категории</a>
                        </li>
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'memory:gallery' %}?category={{ category.name }}" style="text-decoration: none;">
                                {{ category.name }}
                            </a>
                            {% if category.memory_set.count == 0 %}
                                <!-- Показать ссылку на удаление, если в категории нет памяти -->
                                <a href="{% url 'memory:delete_category' category.id %}">
                                    <span class="badge badge-danger" style="float: right; font-size: 1em; color: red;">&times;</span>
                                </a>
                            {% endif %}
                        </li>
                        {% endfor %}
                        
                        <a href="{% url 'memory:add' %}" class="btn btn-dark btn-block btn-sm m-1">Добавить Воспоминание</a>
                    </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">
                    {% for memory in memories %}
                        {% if memories|length <= 4 %}
                            <style>
                                .hak {
                                    position: absolute;
                                }
                            </style>
                        {% elif  5 <= memories|length <= 5 %}
                            <style>
                                .hak {
                                    position: static;
                                }

                            </style>
                        {% endif %}
                        <div class="col-md-3">
                            <div class="card my-2 sev">
                                <img class="image-thumbail" src="{{memory.image.url}}" alt="Card image cap">
                                <div class="card-body">
                                    <small style="color: white;">{{ memory.title }}</small>
                                </div>
                                <div class="card-body">
                                    <small style="color: white;">Категория: {{memory.category.name}}</small>
                                </div>
                                <a href="{% url 'memory:remembering' memory.id %}" class="btn btn-outline-dark btn-sm m-1" style="color: white;">Подробнее</a>
                            </div>
                        </div>
                    {% empty %}
                        <style>
                            .hak {
                                position: absolute;
                            }
                        </style>
                        <h3 style="color: white; text-align: center;">Нет Воспоминаний...</h3>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

memory/templates/memory/remembering.html
{% extends "memory/base.html" %}

{% block title %}{{ memory.title }}{% endblock title%}

{% block content %}
<style>
    .hak{
        position: static;
    }
    .col h3 {
        color: white;
    }
    .col p {
        color: white;
    }
</style>
<div class="m-5">
    <div class="container">
        <div>
            <div class="col">
                <div class="row justify-content-center">
                    <div class="col">
                        <img src="{{memory.image.url}}" class="image">
                        
                    </div>
                    <div class="col">
                        <h3>{{ memory.title }}</h3>
                        <div class="program-inner">
                            <p>{{ memory.description}}</p>
                        </div>
                    </div>
                </div>
                <hr>
                <div id="map" style="height: 300px; width: 100%; margin-bottom: 10%;">
                    <p>{{ memory.address }}</p>
                </div>
                <div class="row justify-content-start">
                    <div class="col">
                        <a href="{% url 'memory:gallery' %}" 
                        class="btn btn-dark my-3">Вернутся в галлерею</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:update' memory.id %}" 
                        class="btn btn-info my-3">Редактировать</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:delete' memory.id %}" 
                        class="btn btn-danger my-3">Удалить</a>
                    </div>
                </div>    
                

            </div>
        </div>
    </div>
</div>
<script src="https://api-maps.yandex.ru/2.1/?apikey=6f23e260-3f4c-4ffb-9804-554d9b4dcbf9&lang=ru_RU" type="text/javascript"></script>
                
<script>
    ymaps.ready(function () {
        var latitude = "{{ memory.latitude }}".replace(',', '.');
        console.log(latitude);
        var longitude = "{{ memory.longitude }}".replace(',', '.');
        console.log(longitude);
        console.log(parseFloat(latitude))
        var map = new ymaps.Map('map', {
            center: [parseFloat(latitude), parseFloat(longitude)],
            zoom: 8
        });
        var placemark = new ymaps.Placemark([parseFloat(latitude), parseFloat(longitude)], {
            hintContent: '{{ memory.address }}'
        });

        map.geoObjects.add(placemark);
    });
</script>
{% endblock content%}

save_memories/memory/templates/memory/remembering.html
{% extends "memory/base.html" %}

{% block title %}{{ memory.title }}{% endblock title%}

{% block content %}
<style>
    .hak{
        position: static;
    }
    .col h3 {
        color: white;
    }
    .col p {
        color: white;
    }
</style>
<div class="m-5">
    <div class="container">
        <div>
            <div class="col">
                <div class="row justify-content-center">
                    <div class="col">
                        <img src="{{memory.image.url}}" class="image">
                        
                    </div>
                    <div class="col">
                        <h3>{{ memory.title }}</h3>
                        <div class="program-inner">
                            <p>{{ memory.description}}</p>
                        </div>
                    </div>
                </div>
                <hr>
                <div id="map" style="height: 300px; width: 100%; margin-bottom: 10%;">
                    <p>{{ memory.address }}</p>
                </div>
                <div class="row justify-content-start">
                    <div class="col">
                        <a href="{% url 'memory:gallery' %}" 
                        class="btn btn-dark my-3">Вернутся в галлерею</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:update' memory.id %}" 
                        class="btn btn-info my-3">Редактировать</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:delete' memory.id %}" 
                        class="btn btn-danger my-3">Удалить</a>
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>
<script src="https://api-maps.yandex.ru/2.1/?apikey=6f23e260-3f4c-4ffb-9804-554d9b4dcbf9&lang=ru_RU" type="text/javascript"></script>
                
<script>
    ymaps.ready(function () {
        var latitude = "{{ memory.latitude }}".replace(',', '.');
        console.log(latitude);
        var longitude = "{{ memory.longitude }}".replace(',', '.');
        console.log(longitude);
        console.log(parseFloat(latitude))
        var map = new ymaps.Map('map', {
            center: [parseFloat(latitude), parseFloat(longitude)],
            zoom: 8
        });
        var placemark = new ymaps.Placemark([parseFloat(latitude), parseFloat(longitude)], {
            hintContent: '{{ memory.address }}'
        });

        map.geoObjects.add(placemark);
    });
</script>
{% endblock content%}

save_memories/save_memories/memory/templates/memory/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'memory/css/memory.css' %}">
    <style>
        .image-thumbail {
            height: 200px;
            object-fit: cover;
        }
        body {
            background-image: url("{% static 'memory/images/forest.jpg'%}");
        }
    </style>
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="#"><p>Places Remember</p></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="nav justify-content-end" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        {% if user.first_name %}
                            Пользователь {{ user.first_name }} авторезирован
                            <a href="{% url 'memory:logout' %}?next={% url 'memory:index' %}" style="text-decoration: none;">Выйти из аккаунта</a>
                        {% else %}
                            Пользователь {{ user.username }} авторезирован
                            <a href="{% url 'memory:logout' %}?next={% url 'memory:index' %}" style="text-decoration: none;">Выйти из аккаунта</a>
                        {% endif %}
                        {% else %}
                            
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    
    
    {% block content %}
    {% endblock content%}
    
</body>
</html>

save_memories/save_memories/memory/templates/memory/gallery.html
{% extends "memory/base.html" %}

{% block title %}Галлерея{% endblock title%}
{% block content %}
<div class="m-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <div class="card">
                    <div class="card-header">
                    Категории
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <a href="{% url 'memory:gallery' %}" style="text-decoration: none;">Все Категории</a>
                        </li>
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'memory:gallery' %}?category={{ category.name }}" style="text-decoration: none;">
                                {{ category.name }}
                            </a>
                            {% if category.memory_set.count == 0 %}
                                <!-- Показать ссылку на удаление, если в категории нет памяти -->
                                <a href="{% url 'memory:delete_category' category.id %}">
                                    <span class="badge badge-danger" style="float: right; font-size: 1em; color: red;">&times;</span>
                                </a>
                            {% endif %}
                        </li>
                        {% endfor %}
                        
                        <a href="{% url 'memory:add' %}" class="btn btn-dark btn-block btn-sm m-1">Добавить Воспоминание</a>
                    </ul>
                </div>

            </div>
            <div class="col-md-9">
                <div class="row">
                    {% for memory in memories %}
                    <div class="col-md-4">
                        <div class="card my-2">
                            <img class="image-thumbail" src="{{memory.image.url}}" alt="Card image cap">
                            <div class="card-body">
                                <small>{{ memory.title }}</small>
                            </div>
                            <div class="card-body">
                                <small>Категория: {{memory.category.name}}</small>
                            </div>
                            <a href="{% url 'memory:remembering' memory.id %}" class="btn btn-outline-dark btn-sm m-1">Подробнее</a>
                        </div>
                    </div>
                    {% empty %}
                        <h3>Нет Воспоминаний...</h3>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

save_memories/save_memories/memory/templates/memory/remembering.html
{% extends "memory/base.html" %}

{% block title %}{{ memory.title }}{% endblock title%}

{% block content %}
<div class="m-5">
    <div class="container">
        <div>
            <div class="col">
                <div class="row justify-content-center">
                    <div class="col">
                        <img style="max-width: 100%; max-height: 100%;"
                            src="{{memory.image.url}}">
                        
                    </div>
                    <div class="col">
                        <p>{{ memory.title }}</p>
                        <p>{{ memory.description}}</p>
                    </div>
                </div>
                <div id="map" style="height: 300px; width: 100%; margin-bottom: 10%;">
                    <p>{{ memory.address }}</p>
                </div>
                <div class="row justify-content-start">
                    <div class="col">
                        <a href="{% url 'memory:gallery' %}" 
                        class="btn btn-dark my-3">Вернутся в галлерею</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:update' memory.id %}" 
                        class="btn btn-info my-3">Редактировать</a>
                    </div>
                    <div class="col">
                        <a href="{% url 'memory:delete' memory.id %}" 
                        class="btn btn-danger my-3">Удалить</a>
                    </div>
                </div>    
                <script src="https://api-maps.yandex.ru/2.1/?apikey=6f23e260-3f4c-4ffb-9804-554d9b4dcbf9&lang=ru_RU" type="text/javascript"></script>
                
                <script>
                    ymaps.ready(function () {
                        var latitude = "{{ memory.latitude }}".replace(',', '.');
                        console.log(latitude);
                        var longitude = "{{ memory.longitude }}".replace(',', '.');
                        console.log(longitude);
                        console.log(parseFloat(latitude))
                        var map = new ymaps.Map('map', {
                            center: [parseFloat(latitude), parseFloat(longitude)],
                            zoom: 8
                        });
                        var placemark = new ymaps.Placemark([parseFloat(latitude), parseFloat(longitude)], {
                            hintContent: '{{ memory.address }}'
                        });
                
                        map.geoObjects.add(placemark);
                    });
                </script>

            </div>
        </div>
    </div>
</div>
{% endblock content%}